# Generated by Django 4.1.6 on 2023-02-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_task_due_date_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
